# Generated by Django 4.1.4 on 2022-12-29 18:25

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todoapp', '0002_rename_prty_task_priority'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='note',
            field=models.TextField(default=datetime.datetime(2022, 12, 29, 23, 55, 27, 453574)),
            preserve_default=False,
        ),
    ]
